SHARED_MEM_BASE					= (0xA0400000);

SHM_AVB_DATA_RX_SIZE		    = (0x80000);  /* 512kB  */
SHM_AVB_DATA_TX_SIZE		    = (0x80000);  /* 512kB  */
SHM_AVB_CNTL_RX_SIZE		    = (0x02000);  /* 8kB    */
SHM_AVB_CNTL_TX_SIZE		    = (0x02000);  /* 8kB    */
SHM_C7A53_SHARED_HEAP_SIZE      = (0x08000);  /* 32kB   */
SHM_TUNING_PKT_SIZE     		= (0x00800);  /* 2 kB   */
SHM_SHARED_LOG_SIZE     		= (0x3E800);  /* 200 kB */

SHM_AVB_DATA_RX_BASE            = (SHARED_MEM_BASE);
SHM_AVB_DATA_TX_BASE            = (SHM_AVB_DATA_RX_BASE + SHM_AVB_DATA_RX_SIZE);
SHM_AVB_CNTL_RX_BASE            = (SHM_AVB_DATA_TX_BASE + SHM_AVB_DATA_TX_SIZE);
SHM_AVB_CNTL_TX_BASE            = (SHM_AVB_CNTL_RX_BASE + SHM_AVB_CNTL_RX_SIZE);
SHM_C7A53_SHARED_HEAP_BASE      = (SHM_AVB_CNTL_TX_BASE + SHM_AVB_CNTL_TX_SIZE);
SHM_TUNING_PKT_BASE             = (SHM_C7A53_SHARED_HEAP_BASE + SHM_C7A53_SHARED_HEAP_SIZE);
SHM_SHARED_LOG_BASE             = (SHM_TUNING_PKT_BASE + SHM_TUNING_PKT_SIZE);
