# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.26)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS ical ical-static ical_cxx ical_cxx-static icalss icalss-static icalss_cxx icalss_cxx-static icalvcal icalvcal-static ical-glib ical-glib-static)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
# Use original install prefix when loaded through a
# cross-prefix symbolic link such as /lib -> /usr/lib.
get_filename_component(_realCurr "${_IMPORT_PREFIX}" REALPATH)
get_filename_component(_realOrig "/usr/lib/cmake/LibIcal" REALPATH)
if(_realCurr STREQUAL _realOrig)
  set(_IMPORT_PREFIX "/usr/lib/cmake/LibIcal")
endif()
unset(_realOrig)
unset(_realCurr)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target ical
add_library(ical SHARED IMPORTED)

set_target_properties(ical PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "/usr/lib/libicuuc.so;/usr/lib/libicui18n.so"
)

# Create imported target ical-static
add_library(ical-static STATIC IMPORTED)

# Create imported target ical_cxx
add_library(ical_cxx SHARED IMPORTED)

set_target_properties(ical_cxx PROPERTIES
  INTERFACE_LINK_LIBRARIES "ical"
)

# Create imported target ical_cxx-static
add_library(ical_cxx-static STATIC IMPORTED)

# Create imported target icalss
add_library(icalss SHARED IMPORTED)

set_target_properties(icalss PROPERTIES
  INTERFACE_LINK_LIBRARIES "ical"
)

# Create imported target icalss-static
add_library(icalss-static STATIC IMPORTED)

# Create imported target icalss_cxx
add_library(icalss_cxx SHARED IMPORTED)

set_target_properties(icalss_cxx PROPERTIES
  INTERFACE_LINK_LIBRARIES "icalss;ical_cxx"
)

# Create imported target icalss_cxx-static
add_library(icalss_cxx-static STATIC IMPORTED)

# Create imported target icalvcal
add_library(icalvcal SHARED IMPORTED)

set_target_properties(icalvcal PROPERTIES
  INTERFACE_LINK_LIBRARIES "ical"
)

# Create imported target icalvcal-static
add_library(icalvcal-static STATIC IMPORTED)

# Create imported target ical-glib
add_library(ical-glib SHARED IMPORTED)

# Create imported target ical-glib-static
add_library(ical-glib-static STATIC IMPORTED)

set_target_properties(ical-glib-static PROPERTIES
  INTERFACE_COMPILE_OPTIONS "-I/usr/include;-I/usr/include/glib-2.0;-I/usr/lib/glib-2.0/include;-I/usr/include;-DG_LOG_DOMAIN=\"libical-glib\";-DLIBICAL_GLIB_COMPILATION"
  INTERFACE_LINK_LIBRARIES "-L/usr/lib;-lgobject-2.0;-lglib-2.0"
)

if(CMAKE_VERSION VERSION_LESS 2.8.12)
  message(FATAL_ERROR "This file relies on consumers using CMake 2.8.12 or greater.")
endif()

# Load information for each installed configuration.
file(GLOB _cmake_config_files "${CMAKE_CURRENT_LIST_DIR}/LibIcalTargets-*.cmake")
foreach(_cmake_config_file IN LISTS _cmake_config_files)
  include("${_cmake_config_file}")
endforeach()
unset(_cmake_config_file)
unset(_cmake_config_files)

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(_cmake_target IN LISTS _cmake_import_check_targets)
  foreach(_cmake_file IN LISTS "_cmake_import_check_files_for_${_cmake_target}")
    if(NOT EXISTS "${_cmake_file}")
      message(FATAL_ERROR "The imported target \"${_cmake_target}\" references the file
   \"${_cmake_file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_cmake_file)
  unset("_cmake_import_check_files_for_${_cmake_target}")
endforeach()
unset(_cmake_target)
unset(_cmake_import_check_targets)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
